version: "3.9"

services:
  crudapp:
    build: .
    container_name: crudapp-tomcat
    restart: always
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"